name: Cub Scouts Pack 770
tagline: Huber Ridge, Westerville, Ohio
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "smart"]
pygments: false
timezone: America/Detroit
future: false
safe: true
paginate: 5
